#!/bin/bash
# Script to migrate Git repository with full history

# Function to read user input if not passed as parameter
read_if_empty() {
  local var_name=$1
  local prompt=$2
  local default_value=$3
  local value=${!var_name}

  if [ -z "$value" ]; then
    read -p "$prompt " value
    # Usa valor padrão se fornecido
    if [ -z "$value" ] && [ -n "$default_value" ]; then
      value=$default_value
    fi
    eval $var_name="'$value'"
  fi
}

ORIGEM=$1
DESTINO=$2
CHECKOUT=$3

read_if_empty ORIGEM "Enter the source repository URL:"
read_if_empty DESTINO "Enter the destination repository URL:"
read_if_empty CHECKOUT "Do you want to clone the destination repository as working copy? (y/n)" "n"

if [[ "$CHECKOUT" =~ ^[Yy]$ ]]; then
  CHECKOUT=true
else
  CHECKOUT=false
fi

echo "=== Cloning the source repository: $SOURCE ==="
git clone --mirror "$SOURCE"
if [ $? -ne 0 ]; then
  echo "Error cloning source repository."
  exit 1
fi

# Extracts the name of the folder generated by the clone
REPO_DIR=$(basename "$SOURCE")
REPO_DIR="${REPO_DIR%.git}.git"

cd "$REPO_DIR" || { echo "Error entering folder $REPO_DIR"; exit 1; }

echo "=== Setting up remote for new repository: $DESTINATION ==="
git remote set-url origin "$DESTINATION"

echo "=== Sending history, branches, and tags to the destination ==="
git push --mirror
if [ $? -ne 0 ]; then
  echo "Error sending to destination."
  exit 1
fi

echo "=== Migration completed successfully! ==="

if [ "$CHECKOUT" = true ]; then
  echo "=== Cloning destination repository with working tree ==="
  cd .. || exit 1
  git clone "$DESTINATION"
  if [ $? -ne 0 ]; then
    echo "Error cloning working copy from destination."
    exit 1
  fi
  echo "=== Working copy of destination repository is ready! ==="
fi
