#!/bin/bash
# Script to migrate Git repository with full history

# Checks if the necessary parameters were passed
if [ "$#" -ne 2 ]; then
  echo "Use: $0 <source_repository_url> <destination_repository_url>"
  exit 1
fi

SOURCE=$1
DESTINATION=$2

echo "=== Cloning the source repository: $SOURCE ==="
git clone --mirror "$SOURCE"
if [ $? -ne 0 ]; then
  echo "Error cloning source repository."
  exit 1
fi

# Extracts the name of the folder generated by the clone
REPO_DIR=$(basename "$SOURCE")
REPO_DIR="${REPO_DIR%.git}.git"

cd "$REPO_DIR" || { echo "Error entering folder $REPO_DIR"; exit 1; }

echo "=== Setting up remote for new repository: $DESTINATION ==="
git remote set-url origin "$DESTINATION"

echo "=== Sending history, branches, and tags to the destination ==="
git push --mirror
if [ $? -ne 0 ]; then
  echo "Error sending to destination."
  exit 1
fi

echo "=== Migration completed successfully! ==="
